---
description: 了解以下内容： "Finally" 不能出现在 "Try" 语句之外
title: “Finally”不能出现在“Try”语句之外
ms.date: 07/20/2015
f1_keywords:
- vbc30382
- bc30382
helpviewer_keywords:
- BC30382
ms.assetid: 0314d8d2-18bc-4bbd-858c-0a18408b52fd
ms.openlocfilehash: 5255cf3e99faf019ce8313f75425cf18b9c9d80d
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 02/14/2021
ms.locfileid: "100472158"
---
# <a name="finally-cannot-appear-outside-a-try-statement"></a>“Finally”不能出现在“Try”语句之外

`Finally` 用于完成 `Try...Catch...Finally` 块；因此它只能在块的末尾出现一次。 或者有不必要的 `Finally`，或者 `Finally` 语句出现在其对应 `Try` 块的边界之外。  
  
 **错误 ID:** BC30382  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
1. 找到并删除不必要的 `Finally` 语句。  
  
2. 将 `Finally` 语句移到代码中的适当位置。  
  
## <a name="see-also"></a>另请参阅

- [Try...Catch...Finally 语句](../language-reference/statements/try-catch-finally-statement.md)
