---
description: 了解详细信息：永远不会到达 "Catch" 块;已 <exception> 在相同的 "Try" 语句中处理
title: 永远不会到达“Catch”块；<exception> 已在上面同一个 Try 语句中处理
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: fc52c21f7a319c26b6ca7128c8d2d781db1a58c1
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 02/14/2021
ms.locfileid: "100473015"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a><span data-ttu-id="f3966-103">永远不会到达“Catch”块；\<exception> 已在上面同一个 Try 语句中处理</span><span class="sxs-lookup"><span data-stu-id="f3966-103">'Catch' block never reached; \<exception> handled above in the same 'Try' statement</span></span>

<span data-ttu-id="f3966-104">无法达到代码中的 `Catch` 块，因为它已经在前面的 `Try` 块中得到处理。</span><span class="sxs-lookup"><span data-stu-id="f3966-104">A `Catch` block in the code cannot be reached because it is handled in a preceding `Try` block.</span></span>  
  
<span data-ttu-id="f3966-105">默认情况下，此消息是一个警告。</span><span class="sxs-lookup"><span data-stu-id="f3966-105">By default, this message is a warning.</span></span> <span data-ttu-id="f3966-106">有关隐藏警告或将警告视为错误的详细信息，请参阅 [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)。</span><span class="sxs-lookup"><span data-stu-id="f3966-106">For more information about hiding warnings or treating warnings as errors, see [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).</span></span>
  
 <span data-ttu-id="f3966-107">**错误 ID：** BC42031</span><span class="sxs-lookup"><span data-stu-id="f3966-107">**Error ID:** BC42031</span></span>  
  
## <a name="to-correct-this-error"></a><span data-ttu-id="f3966-108">更正此错误</span><span class="sxs-lookup"><span data-stu-id="f3966-108">To correct this error</span></span>  
  
- <span data-ttu-id="f3966-109">删除多余的语句。</span><span class="sxs-lookup"><span data-stu-id="f3966-109">Remove the redundant statement.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="f3966-110">请参阅</span><span class="sxs-lookup"><span data-stu-id="f3966-110">See also</span></span>

- [<span data-ttu-id="f3966-111">如何使用 try/catch 块捕获异常</span><span class="sxs-lookup"><span data-stu-id="f3966-111">How to use the try/catch block to catch exceptions</span></span>](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [<span data-ttu-id="f3966-112">使用用户筛选的异常处理程序</span><span class="sxs-lookup"><span data-stu-id="f3966-112">Using User-Filtered Exception Handlers</span></span>](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [<span data-ttu-id="f3966-113">Try...Catch...Finally 语句</span><span class="sxs-lookup"><span data-stu-id="f3966-113">Try...Catch...Finally Statement</span></span>](../language-reference/statements/try-catch-finally-statement.md)
